### ISSUE TITLE
help me to error './platform/win32.json'

### ISSUE THREAD

**Issue by asgdestroi** [robinsloan/rnn-writer#8]
After running all the commands using Git Bash when Atom opens the following error appears:

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [rnn-writer](https://github.com/robinsloan/rnn-writer) package 0.0.1

### Stack Trace

Failed to load the rnn-writer package

```
At Cannot find module './platform/win32.json'

Error: Cannot find module './platform/win32.json'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.init (~/rnn-writer/node_modules/sfx/sfx.js:163:43)
    at Object.<anonymous> (~/rnn-writer/node_modules/sfx/sfx.js:193:22)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (~/rnn-writer/lib/rnn-writer.coffee:4:7)
    at Object.<anonymous> (~/rnn-writer/lib/rnn-writer.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.18.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:565:22)
    at PackageManager.module.exports.PackageManager.loadPackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:495:27)
```

### Commands

```
```

### Non-Core Packages

```
img undefined 
keymaps undefined 
lib undefined 
menus undefined 
rnn-writer 0.0.1 
styles undefined 
```

**Comment by robinsloan** [comment]
As far as I can tell, that's a Windows-specific error with the `sfx` package that I use to play sounds. I think I can fix it by only including the package (and playing the sound effects) when running on Mac or Linux. I don't have time to make those changes right now but with luck I'll be able to do it soon… and in the meantime if you just comment out all the references to `sfx` things should work again! (But of course, let me know if that's not the case.)
